package sudoku.engine

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

/**
 * GraderTest verifies that known reference puzzles grade to the expected Difficulty level.
 *
 * Grading thresholds:
 *   EASY   — solvable with naked singles + hidden singles only
 *   MEDIUM — additionally requires naked pairs or hidden pairs
 *   HARD   — additionally requires pointing pairs
 *   EXPERT — additionally requires X-Wing (or puzzle is unsolvable by the above)
 *
 * Puzzle sources: generated by Generator and verified by Grader.grade() + Solver.countSolutions().
 *
 * Degenerate case: the all-zeros empty board returns EXPERT because the grader exhausts
 * all technique tiers and still cannot place any digit (no givens → no constraints →
 * no technique fires), so it falls through to the final EXPERT return statement.
 */
class GraderTest {

    // -------------------------------------------------------------------------
    // EASY reference puzzle
    // Classic "newspaper" puzzle — solvable entirely by naked singles + hidden singles.
    // Source: widely published in public domain (Peter Norvig's Sudoku page).
    // -------------------------------------------------------------------------
    private val easyPuzzle = intArrayOf(
        5,3,0, 0,7,0, 0,0,0,
        6,0,0, 1,9,5, 0,0,0,
        0,9,8, 0,0,0, 0,6,0,
        8,0,0, 0,6,0, 0,0,3,
        4,0,0, 8,0,3, 0,0,1,
        7,0,0, 0,2,0, 0,0,6,
        0,6,0, 0,0,0, 2,8,0,
        0,0,0, 4,1,9, 0,0,5,
        0,0,0, 0,8,0, 0,7,9,
    )

    // -------------------------------------------------------------------------
    // MEDIUM reference puzzle
    // Requires naked/hidden pairs to resolve; naked+hidden singles alone stall.
    // Generated and grade-verified by the engine.
    // -------------------------------------------------------------------------
    private val mediumPuzzle = intArrayOf(
        0,0,5, 0,4,9, 0,0,0,
        0,7,0, 1,8,0, 0,0,0,
        0,0,8, 0,0,3, 0,1,0,
        8,0,0, 0,0,4, 0,0,3,
        0,0,0, 5,0,0, 7,6,0,
        0,0,6, 0,0,8, 0,4,0,
        0,0,0, 0,0,7, 0,8,2,
        0,0,0, 0,2,0, 0,0,0,
        0,5,0, 0,0,0, 0,3,9,
    )

    // -------------------------------------------------------------------------
    // HARD reference puzzle
    // Requires pointing pairs to make progress after naked/hidden pairs stall.
    // Generated and grade-verified by the engine.
    // -------------------------------------------------------------------------
    private val hardPuzzle = intArrayOf(
        0,0,7, 4,8,0, 0,6,0,
        0,0,0, 0,0,0, 0,0,2,
        0,1,0, 0,7,2, 4,9,0,
        0,5,0, 0,1,9, 8,0,0,
        0,3,0, 0,0,0, 0,0,0,
        8,0,0, 2,0,0, 0,0,0,
        0,0,3, 0,2,7, 0,0,6,
        0,0,6, 0,0,0, 9,0,0,
        9,2,0, 8,0,0, 1,0,7,
    )

    // -------------------------------------------------------------------------
    // EXPERT reference puzzle
    // Requires X-Wing or beyond; pointing pairs are insufficient.
    // Generated and grade-verified by the engine.
    // -------------------------------------------------------------------------
    private val expertPuzzle = intArrayOf(
        6,7,0, 3,9,0, 0,0,0,
        0,0,5, 0,7,0, 0,1,4,
        0,0,0, 0,0,0, 0,0,6,
        0,2,0, 0,0,0, 0,8,5,
        0,0,3, 0,0,7, 0,0,0,
        0,4,0, 0,0,2, 0,6,0,
        3,9,0, 2,8,0, 0,0,0,
        8,0,0, 0,0,0, 0,0,9,
        0,0,0, 0,4,0, 0,0,1,
    )

    @Test
    fun `known Easy puzzle grades as EASY`() {
        assertEquals(Difficulty.EASY, Grader.grade(easyPuzzle))
    }

    @Test
    fun `known Medium puzzle grades as MEDIUM`() {
        assertEquals(Difficulty.MEDIUM, Grader.grade(mediumPuzzle))
    }

    @Test
    fun `known Hard puzzle grades as HARD`() {
        assertEquals(Difficulty.HARD, Grader.grade(hardPuzzle))
    }

    @Test
    fun `known Expert puzzle grades as EXPERT`() {
        assertEquals(Difficulty.EXPERT, Grader.grade(expertPuzzle))
    }

    /**
     * Degenerate case: empty board (all zeros).
     * The grader receives no constraints, so no technique can place any digit.
     * All technique tiers are exhausted without progress and the function returns EXPERT
     * (the final fall-through return value in Grader.grade).
     */
    @Test
    fun `empty board grades as EXPERT`() {
        assertEquals(Difficulty.EXPERT, Grader.grade(IntArray(81)))
    }
}
