package sudoku.engine

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

/**
 * GraderTest verifies that known reference puzzles grade to the expected Difficulty level.
 *
 * Grading thresholds:
 *   EASY   — solvable with naked singles + hidden singles only
 *   MEDIUM — additionally requires naked/hidden pairs or pointing pairs
 *   HARD   — additionally requires naked/hidden triples
 *   EXPERT — additionally requires X-Wing or Swordfish (or puzzle is unsolvable by the above)
 *
 * Puzzle sources: generated by Generator and verified by Grader.grade() + Solver.countSolutions().
 *
 * Degenerate case: the all-zeros empty board returns EXPERT because the grader exhausts
 * all technique tiers and still cannot place any digit (no givens → no constraints →
 * no technique fires), so it falls through to the final EXPERT return statement.
 */
class GraderTest {

    // -------------------------------------------------------------------------
    // EASY reference puzzle
    // Classic "newspaper" puzzle — solvable entirely by naked singles + hidden singles.
    // Source: widely published in public domain (Peter Norvig's Sudoku page).
    // -------------------------------------------------------------------------
    private val easyPuzzle = intArrayOf(
        5,3,0, 0,7,0, 0,0,0,
        6,0,0, 1,9,5, 0,0,0,
        0,9,8, 0,0,0, 0,6,0,
        8,0,0, 0,6,0, 0,0,3,
        4,0,0, 8,0,3, 0,0,1,
        7,0,0, 0,2,0, 0,0,6,
        0,6,0, 0,0,0, 2,8,0,
        0,0,0, 4,1,9, 0,0,5,
        0,0,0, 0,8,0, 0,7,9,
    )

    // -------------------------------------------------------------------------
    // MEDIUM reference puzzle
    // Requires naked/hidden pairs to resolve; naked+hidden singles alone stall.
    // Generated and grade-verified by the engine.
    // -------------------------------------------------------------------------
    private val mediumPuzzle = intArrayOf(
        0,0,5, 0,4,9, 0,0,0,
        0,7,0, 1,8,0, 0,0,0,
        0,0,8, 0,0,3, 0,1,0,
        8,0,0, 0,0,4, 0,0,3,
        0,0,0, 5,0,0, 7,6,0,
        0,0,6, 0,0,8, 0,4,0,
        0,0,0, 0,0,7, 0,8,2,
        0,0,0, 0,2,0, 0,0,0,
        0,5,0, 0,0,0, 0,3,9,
    )

    // -------------------------------------------------------------------------
    // HARD reference puzzle
    // Requires naked/hidden triples to make progress after pairs/pointing-pairs stall.
    // Generated and grade-verified by the engine.
    // -------------------------------------------------------------------------
    private val hardPuzzle = intArrayOf(
        0,5,0, 0,0,0, 2,9,3,
        7,0,0, 0,0,0, 8,0,0,
        0,0,2, 0,0,1, 0,5,0,
        0,2,0, 0,6,0, 0,3,4,
        3,0,0, 0,0,4, 0,0,7,
        0,0,0, 9,0,0, 0,0,0,
        0,7,0, 3,8,0, 0,0,0,
        0,6,0, 0,0,0, 0,1,0,
        0,0,0, 0,5,9, 0,0,0,
    )

    // -------------------------------------------------------------------------
    // EXPERT/Swordfish reference puzzle
    // Requires Swordfish to make progress after X-Wing is insufficient.
    // Generated and grade-verified by the engine.
    // -------------------------------------------------------------------------
    private val sworfishPuzzle = intArrayOf(
        0,0,9, 0,6,0, 0,5,0,
        8,0,0, 0,7,0, 0,9,0,
        5,0,0, 0,0,8, 7,0,4,
        4,0,0, 0,0,5, 0,7,0,
        0,0,0, 1,0,6, 0,0,0,
        0,5,0, 9,0,0, 0,3,0,
        0,0,0, 0,0,3, 0,0,1,
        0,0,0, 4,0,0, 0,0,0,
        0,0,8, 0,0,0, 9,0,3,
    )

    // -------------------------------------------------------------------------
    // EXPERT reference puzzle
    // Requires X-Wing or beyond; pointing pairs are insufficient.
    // Generated and grade-verified by the engine.
    // -------------------------------------------------------------------------
    private val expertPuzzle = intArrayOf(
        6,7,0, 3,9,0, 0,0,0,
        0,0,5, 0,7,0, 0,1,4,
        0,0,0, 0,0,0, 0,0,6,
        0,2,0, 0,0,0, 0,8,5,
        0,0,3, 0,0,7, 0,0,0,
        0,4,0, 0,0,2, 0,6,0,
        3,9,0, 2,8,0, 0,0,0,
        8,0,0, 0,0,0, 0,0,9,
        0,0,0, 0,4,0, 0,0,1,
    )

    @Test
    fun `known Easy puzzle grades as EASY`() {
        assertEquals(Difficulty.EASY, Grader.grade(easyPuzzle))
    }

    @Test
    fun `known Medium puzzle grades as MEDIUM`() {
        assertEquals(Difficulty.MEDIUM, Grader.grade(mediumPuzzle))
    }

    @Test
    fun `known Hard puzzle grades as HARD`() {
        assertEquals(Difficulty.HARD, Grader.grade(hardPuzzle))
    }

    @Test
    fun `known Expert puzzle grades as EXPERT`() {
        assertEquals(Difficulty.EXPERT, Grader.grade(expertPuzzle))
    }

    /**
     * Degenerate case: empty board (all zeros).
     * The grader receives no constraints, so no technique can place any digit.
     * All technique tiers are exhausted without progress and the function returns EXPERT
     * (the final fall-through return value in Grader.grade).
     */
    @Test
    fun `empty board grades as EXPERT`() {
        assertEquals(Difficulty.EXPERT, Grader.grade(IntArray(81)))
    }

    // -------------------------------------------------------------------------
    // Unit tests for new techniques
    // -------------------------------------------------------------------------

    /**
     * applyNakedTriples: cells 0/1/2 in row 0 form a naked triple {1,2}, {2,3}, {1,3}.
     * Cell 3 has {1,2,4}. After the technique, cell 3 must be reduced to {4} only.
     */
    @Test
    fun `applyNakedTriples eliminates candidates`() {
        val candidates = IntArray(81) { 0 }
        val digits = IntArray(81) { 0 }
        candidates[0] = (1 shl 1) or (1 shl 2)                         // {1,2}
        candidates[1] = (1 shl 2) or (1 shl 3)                         // {2,3}
        candidates[2] = (1 shl 1) or (1 shl 3)                         // {1,3}
        candidates[3] = (1 shl 1) or (1 shl 2) or (1 shl 4)            // {1,2,4}
        val progress = Grader.applyNakedTriples(candidates, digits)
        assertEquals(true, progress)
        assertEquals(1 shl 4, candidates[3])                            // only 4 remains
    }

    /**
     * applyHiddenTriples: digits 7/8/9 each appear in exactly cells 0/1/2 of row 0.
     * Those cells also carry extra candidates 1/2. After the technique, cells 0/1/2
     * must be stripped to contain only their triple digits.
     *
     * Setup: cells 3-8 hold {1,2} so that digit 1 and 2 appear widely (not hidden).
     * Digit 7 in {0,1}, digit 8 in {1,2}, digit 9 in {0,2} — union = {0,1,2}.
     */
    @Test
    fun `applyHiddenTriples eliminates candidates`() {
        val candidates = IntArray(81) { 0 }
        val digits = IntArray(81) { 0 }
        // cell 0: {7,9,1}  cell 1: {7,8,2}  cell 2: {8,9,1}
        candidates[0] = (1 shl 7) or (1 shl 9) or (1 shl 1)
        candidates[1] = (1 shl 7) or (1 shl 8) or (1 shl 2)
        candidates[2] = (1 shl 8) or (1 shl 9) or (1 shl 1)
        // cells 3-8: {1,2} — makes digits 1 and 2 appear widely (≥4 cells each)
        for (i in 3..8) candidates[i] = (1 shl 1) or (1 shl 2)
        val progress = Grader.applyHiddenTriples(candidates, digits)
        assertEquals(true, progress)
        // cells 0/1/2 keep only their triple digits
        assertEquals((1 shl 7) or (1 shl 9), candidates[0])
        assertEquals((1 shl 7) or (1 shl 8), candidates[1])
        assertEquals((1 shl 8) or (1 shl 9), candidates[2])
    }

    /**
     * applySwordfish: digit 5 forms a swordfish across rows 0/3/6, confined to columns 1/4/7.
     * After the technique, digit 5 must be eliminated from columns 1/4/7 in all other rows.
     */
    @Test
    fun `applySwordfish eliminates candidates`() {
        val candidates = IntArray(81) { 0 }
        val digits = IntArray(81) { 0 }
        val bit5 = 1 shl 5
        // Swordfish rows: 0, 3, 6 — digit 5 appears only at columns 1, 4, 7
        for (row in listOf(0, 3, 6)) {
            for (col in listOf(1, 4, 7)) {
                candidates[row * 9 + col] = bit5
            }
        }
        // Non-swordfish rows: rows 1,2,4,5,7,8 — place digit 5 at column 1 to test elimination
        for (row in listOf(1, 2, 4, 5, 7, 8)) {
            candidates[row * 9 + 1] = bit5
        }
        val progress = Grader.applySwordfish(candidates, digits)
        assertEquals(true, progress)
        // Rows 1/2/4/5/7/8 column 1 must now be empty
        for (row in listOf(1, 2, 4, 5, 7, 8)) {
            assertEquals(0, candidates[row * 9 + 1])
        }
    }

    @Test
    fun `known Triples puzzle grades as HARD`() {
        assertEquals(Difficulty.HARD, Grader.grade(hardPuzzle))
    }

    @Test
    fun `known Swordfish puzzle grades as EXPERT`() {
        assertEquals(Difficulty.EXPERT, Grader.grade(sworfishPuzzle))
    }
}
